### ISSUE TITLE
Smarty3が使えないようです

### ISSUE THREAD

**Issue by kawanotron** [ethnamphp/ethnam#11]
Smarty3 が使えなかったので本家 2.6.0-beta4 から差分を埋めて使っています。

**Comment by DQNEO** [comment]
報告ありがとうございます！

**Comment by DQNEO** [comment]
申し訳ないのですが、私自身がSmarty3を使っておらず今後メンテナンスを維持していくのが困難なため、Smarty3は非サポートとさせてください。
結論が遅くなってすみません。
