### ISSUE TITLE
ethna2.6から移行手順について

### ISSUE THREAD

**Issue by bsetsu** [ethnamphp/ethnam#12]
既存のethna2.6のアプリケーションがありますが、ethnamに移行しようと思ってやってみましたが、うまく行きませんでした。
移行についてのガイドや説明などありますか？

**Comment by DQNEO** [comment]
お問合せありがとうございます。
ethnamでは多数の機能が削られましたので、削除された機能を使っている場合は動かない可能性が高いです。
ethna2.5からの変更点はこちらにあります。
https://github.com/DQNEO/ethnam/blob/master/CHANGES.md

具体的にどこがうまく行かないかわかりますでしょうか？

**Comment by DQNEO** [comment]
上記ドキュメントをもって説明のかわりとさせていただきます。
